#+TITLE: README

* Emacs Bitwarden

A Bitwarden command wrapper for Emacs.

** Installation

To use this package you will need the [[https://github.com/bitwarden/cli][Bitwarden CLI]].

** Automatic unlock

Bitwarden has a concept of locking which is different from logging in. For
two-factor authentication, this means that only logging in will require your 2fa
token.

As a convenience, you can store your master password in your OS keychain and use
the [[file:bitwarden.el::(defcustom%20bitwarden-automatic-unlock%20nil][bitwarden-automatic-unlock]] variable. For example, to temporarily set the
=auth-source= to the macos keychain and then query that,

#+BEGIN_SRC emacs-lisp
(setq bitwarden-automatic-unlock
      (let* ((auth-sources '(macos-keychain-internet))
             (matches (auth-source-search :user "sean@farley.io"
                                          :host "bitwarden.farley.in"
                                          :require '(:secret)
                                          :max 1))
             (entry (nth 0 matches)))
        (plist-get entry :secret)))
#+END_SRC

** auth-source

There is read-only support for auth-source as well. You can run
=bitwarden-auth-source-enable= to enable it. For example,

#+BEGIN_SRC emacs-lisp
(auth-source-search :host "github.com")
#+END_SRC

will return all logins that match =github.com=.
